"""Initial canonical schema, tenant constraints and immutable audit records.

This schema is frozen; it intentionally does not import application metadata.
Revision ID: 0001_canonical
"""
from alembic import op
import sqlalchemy as sa

revision = "0001_canonical"
down_revision = None
branch_labels = None
depends_on = None

AUDIT_TABLES = ('action_batches', 'action_events', 'actions', 'agent_findings', 'ai_search_snapshots', 'approvals', 'calibration_records', 'claim_evidence', 'claims', 'crawl_snapshots', 'decision_logs', 'evidence', 'experiment_metrics', 'failure_cases', 'guardrails', 'page_versions', 'policies', 'revisions', 'rollback_events', 'serp_snapshots', 'strategy_versions', 'verifications')

def _audit_triggers():
    dialect = op.get_bind().dialect.name
    if dialect == "postgresql":
        op.execute("""CREATE OR REPLACE FUNCTION seo_reject_audit_mutation() RETURNS trigger
            LANGUAGE plpgsql AS $$ BEGIN
                RAISE EXCEPTION 'append-only canonical record: %', TG_TABLE_NAME;
            END $$;""")
        for table in AUDIT_TABLES:
            op.execute(f'CREATE TRIGGER "{table}_immutable" BEFORE UPDATE OR DELETE ON "{table}" FOR EACH ROW EXECUTE FUNCTION seo_reject_audit_mutation()')
            op.execute(f'CREATE TRIGGER "{table}_no_truncate" BEFORE TRUNCATE ON "{table}" FOR EACH STATEMENT EXECUTE FUNCTION seo_reject_audit_mutation()')
    elif dialect == "sqlite":
        for table in AUDIT_TABLES:
            for operation in ("UPDATE", "DELETE"):
                name = f"{table}_immutable_{operation.lower()}"
                op.execute(f'CREATE TRIGGER "{name}" BEFORE {operation} ON "{table}" BEGIN SELECT RAISE(ABORT, \'append-only canonical record\'); END')


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sites',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('base_url', sa.String(length=2048), nullable=False),
    sa.Column('autonomy_level', sa.Integer(), nullable=False),
    sa.Column('production_enabled', sa.Boolean(), nullable=False),
    sa.Column('conversion_definition', sa.JSON(), nullable=False),
    sa.Column('config_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('autonomy_level BETWEEN 0 AND 5', name=op.f('ck_sites_autonomy_range')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sites')),
    sa.UniqueConstraint('base_url', name=op.f('uq_sites_base_url'))
    )
    op.create_table('action_batches',
    sa.Column('actor', sa.String(length=200), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('manifest_json', sa.JSON(), nullable=False),
    sa.Column('site_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], name=op.f('fk_action_batches_site_id_sites'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_action_batches')),
    sa.UniqueConstraint('id', 'site_id', name='uq_action_batches_id_site')
    )
    op.create_index(op.f('ix_action_batches_site_id'), 'action_batches', ['site_id'], unique=False)
    op.create_table('ai_search_snapshots',
    sa.Column('query', sa.String(length=2048), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('response_json', sa.JSON(), nullable=False),
    sa.Column('citations_json', sa.JSON(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_fixture', sa.Boolean(), nullable=False),
    sa.Column('capability_status', sa.String(length=50), nullable=False),
    sa.Column('site_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], name=op.f('fk_ai_search_snapshots_site_id_sites'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_search_snapshots')),
    sa.UniqueConstraint('id', 'site_id', name='uq_ai_search_snapshots_id_site')
    )
    op.create_index(op.f('ix_ai_search_snapshots_site_id'), 'ai_search_snapshots', ['site_id'], unique=False)
    op.create_table('assumptions',
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('owner', sa.String(length=200), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('impact', sa.Text(), nullable=False),
    sa.Column('falsification_test', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('evidence_ids_json', sa.JSON(), nullable=False),
    sa.Column('site_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], name=op.f('fk_assumptions_site_id_sites'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assumptions')),
    sa.UniqueConstraint('id', 'site_id', name='uq_assumptions_id_site')
    )
    op.create_index(op.f('ix_assumptions_site_id'), 'assumptions', ['site_id'], unique=False)
    op.create_table('claims',
    sa.Column('claim', sa.Text(), nullable=False),
    sa.Column('claim_type', sa.String(length=20), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('evidence_ids_json', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('owner', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('contradicting_evidence_json', sa.JSON(), nullable=False),
    sa.Column('alternative_explanations_json', sa.JSON(), nullable=False),
    sa.Column('supersedes_id', sa.String(length=36), nullable=True),
    sa.Column('site_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("claim_type IN ('FACT','INFERENCE','HYPOTHESIS','ASSUMPTION','DECISION','ACTION')", name=op.f('ck_claims_claim_type')),
    sa.CheckConstraint('confidence BETWEEN 0 AND 1', name=op.f('ck_claims_confidence_range')),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], name=op.f('fk_claims_site_id_sites'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_claims')),
    sa.UniqueConstraint('id', 'site_id', name='uq_claims_id_site')
    )
    op.create_index(op.f('ix_claims_site_id'), 'claims', ['site_id'], unique=False)
    op.create_table('evidence',
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('source_type', sa.String(length=100), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('owner', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('is_fixture', sa.Boolean(), nullable=False),
    sa.Column('site_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('confidence BETWEEN 0 AND 1', name=op.f('ck_evidence_confidence_range')),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], name=op.f('fk_evidence_site_id_sites'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidence')),
    sa.UniqueConstraint('id', 'site_id', name='uq_evidence_id_site')
    )
    op.create_index(op.f('ix_evidence_site_id'), 'evidence', ['site_id'], unique=False)
    op.create_table('job_leases',
    sa.Column('key', sa.String(length=250), nullable=False),
    sa.Column('site_id', sa.String(length=36), nullable=True),
    sa.Column('owner', sa.String(length=200), nullable=False),
    sa.Column('token', sa.String(length=36), nullable=False),
    sa.Column('fencing_token', sa.Integer(), nullable=False),
    sa.Column('acquired_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], name=op.f('fk_job_leases_site_id_sites'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_job_leases'))
    )
    op.create_index(op.f('ix_job_leases_expires_at'), 'job_leases', ['expires_at'], unique=False)
    op.create_table('job_runs',
    sa.Column('job_name', sa.String(length=200), nullable=False),
    sa.Column('idempotency_key', sa.String(length=200), nullable=False),
    sa.Column('owner', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('result_json', sa.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('site_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], name=op.f('fk_job_runs_site_id_sites'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_runs')),
    sa.UniqueConstraint('id', 'site_id', name='uq_job_runs_id_site'),
    sa.UniqueConstraint('site_id', 'job_name', 'idempotency_key', name=op.f('uq_job_runs_site_id'))
    )
    op.create_index(op.f('ix_job_runs_site_id'), 'job_runs', ['site_id'], unique=False)
    op.create_table('mission_states',
    sa.Column('objective', sa.Text(), nullable=False),
    sa.Column('success_criteria_json', sa.JSON(), nullable=False),
    sa.Column('constraints_json', sa.JSON(), nullable=False),
    sa.Column('available_resources_json', sa.JSON(), nullable=False),
    sa.Column('unknowns_json', sa.JSON(), nullable=False),
    sa.Column('blockers_json', sa.JSON(), nullable=False),
    sa.Column('critical_path_json', sa.JSON(), nullable=False),
    sa.Column('resource_budget_json', sa.JSON(), nullable=False),
    sa.Column('autonomy_level', sa.Integer(), nullable=False),
    sa.Column('phase', sa.String(length=100), nullable=False),
    sa.Column('stop_condition', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('site_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], name=op.f('fk_mission_states_site_id_sites'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mission_states')),
    sa.UniqueConstraint('id', 'site_id', name='uq_mission_states_id_site'),
    sa.UniqueConstraint('site_id', name=op.f('uq_mission_states_site_id'))
    )
    op.create_index(op.f('ix_mission_states_site_id'), 'mission_states', ['site_id'], unique=False)
    op.create_table('pages',
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('external_id', sa.String(length=200), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('content_html', sa.Text(), nullable=False),
    sa.Column('meta_description', sa.Text(), nullable=False),
    sa.Column('canonical', sa.String(length=2048), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('indexed_status', sa.String(length=40), nullable=False),
    sa.Column('crawlable', sa.Boolean(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('last_observed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('site_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], name=op.f('fk_pages_site_id_sites'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pages')),
    sa.UniqueConstraint('id', 'site_id', name='uq_pages_id_site'),
    sa.UniqueConstraint('site_id', 'url', name=op.f('uq_pages_site_id'))
    )
    op.create_index(op.f('ix_pages_site_id'), 'pages', ['site_id'], unique=False)
    op.create_table('policies',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('rules_json', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.String(length=200), nullable=False),
    sa.Column('effective_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('site_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], name=op.f('fk_policies_site_id_sites'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_policies')),
    sa.UniqueConstraint('id', 'site_id', name='uq_policies_id_site'),
    sa.UniqueConstraint('site_id', 'name', 'version', name=op.f('uq_policies_site_id'))
    )
    op.create_index(op.f('ix_policies_site_id'), 'policies', ['site_id'], unique=False)
    op.create_table('query_clusters',
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('intent', sa.String(length=100), nullable=False),
    sa.Column('method', sa.String(length=100), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('site_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], name=op.f('fk_query_clusters_site_id_sites'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_query_clusters')),
    sa.UniqueConstraint('id', 'site_id', name='uq_query_clusters_id_site'),
    sa.UniqueConstraint('site_id', 'name', name=op.f('uq_query_clusters_site_id'))
    )
    op.create_index(op.f('ix_query_clusters_site_id'), 'query_clusters', ['site_id'], unique=False)
    op.create_table('serp_snapshots',
    sa.Column('query', sa.String(length=2048), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=False),
    sa.Column('device', sa.String(length=30), nullable=False),
    sa.Column('results_json', sa.JSON(), nullable=False),
    sa.Column('features_json', sa.JSON(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_fixture', sa.Boolean(), nullable=False),
    sa.Column('site_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], name=op.f('fk_serp_snapshots_site_id_sites'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_serp_snapshots')),
    sa.UniqueConstraint('id', 'site_id', name='uq_serp_snapshots_id_site')
    )
    op.create_index('ix_serp_site_query', 'serp_snapshots', ['site_id', 'query'], unique=False)
    op.create_index(op.f('ix_serp_snapshots_site_id'), 'serp_snapshots', ['site_id'], unique=False)
    op.create_table('strategy_versions',
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('objective', sa.Text(), nullable=False),
    sa.Column('strategy_json', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.String(length=200), nullable=False),
    sa.Column('evidence_ids_json', sa.JSON(), nullable=False),
    sa.Column('site_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], name=op.f('fk_strategy_versions_site_id_sites'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_strategy_versions')),
    sa.UniqueConstraint('id', 'site_id', name='uq_strategy_versions_id_site'),
    sa.UniqueConstraint('site_id', 'version', name=op.f('uq_strategy_versions_site_id'))
    )
    op.create_index(op.f('ix_strategy_versions_site_id'), 'strategy_versions', ['site_id'], unique=False)
    op.create_table('claim_evidence',
    sa.Column('claim_id', sa.String(length=36), nullable=False),
    sa.Column('evidence_id', sa.String(length=36), nullable=False),
    sa.Column('relationship', sa.String(length=30), nullable=False),
    sa.Column('site_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['claim_id', 'site_id'], ['claims.id', 'claims.site_id'], name=op.f('fk_claim_evidence_claim_id_claims'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['evidence_id', 'site_id'], ['evidence.id', 'evidence.site_id'], name=op.f('fk_claim_evidence_evidence_id_evidence'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], name=op.f('fk_claim_evidence_site_id_sites'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_claim_evidence')),
    sa.UniqueConstraint('claim_id', 'evidence_id', 'relationship', name=op.f('uq_claim_evidence_claim_id')),
    sa.UniqueConstraint('id', 'site_id', name='uq_claim_evidence_id_site')
    )
    op.create_index(op.f('ix_claim_evidence_site_id'), 'claim_evidence', ['site_id'], unique=False)
    op.create_table('contradictions',
    sa.Column('claim_a_id', sa.String(length=36), nullable=True),
    sa.Column('claim_b_id', sa.String(length=36), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('site_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['claim_a_id', 'site_id'], ['claims.id', 'claims.site_id'], name=op.f('fk_contradictions_claim_a_id_claims'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['claim_b_id', 'site_id'], ['claims.id', 'claims.site_id'], name=op.f('fk_contradictions_claim_b_id_claims'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], name=op.f('fk_contradictions_site_id_sites'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contradictions')),
    sa.UniqueConstraint('id', 'site_id', name='uq_contradictions_id_site')
    )
    op.create_index(op.f('ix_contradictions_site_id'), 'contradictions', ['site_id'], unique=False)
    op.create_table('crawl_snapshots',
    sa.Column('page_id', sa.String(length=36), nullable=True),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('result_json', sa.JSON(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_fixture', sa.Boolean(), nullable=False),
    sa.Column('site_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['page_id', 'site_id'], ['pages.id', 'pages.site_id'], name=op.f('fk_crawl_snapshots_page_id_pages'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], name=op.f('fk_crawl_snapshots_site_id_sites'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_crawl_snapshots')),
    sa.UniqueConstraint('id', 'site_id', name='uq_crawl_snapshots_id_site')
    )
    op.create_index(op.f('ix_crawl_snapshots_site_id'), 'crawl_snapshots', ['site_id'], unique=False)
    op.create_table('experiments',
    sa.Column('page_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('hypothesis', sa.Text(), nullable=False),
    sa.Column('mechanism', sa.Text(), nullable=False),
    sa.Column('primary_outcome', sa.String(length=200), nullable=False),
    sa.Column('secondary_outcomes_json', sa.JSON(), nullable=False),
    sa.Column('baseline_start', sa.Date(), nullable=True),
    sa.Column('baseline_end', sa.Date(), nullable=True),
    sa.Column('deployed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('evaluation_windows_json', sa.JSON(), nullable=False),
    sa.Column('control_pages_json', sa.JSON(), nullable=False),
    sa.Column('predicted_effect', sa.Float(), nullable=True),
    sa.Column('predicted_confidence', sa.Float(), nullable=True),
    sa.Column('actual_effect', sa.Float(), nullable=True),
    sa.Column('alternative_explanations_json', sa.JSON(), nullable=False),
    sa.Column('verdict', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('analysis_json', sa.JSON(), nullable=False),
    sa.Column('site_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('predicted_confidence IS NULL OR predicted_confidence BETWEEN 0 AND 1', name=op.f('ck_experiments_confidence_range')),
    sa.ForeignKeyConstraint(['page_id', 'site_id'], ['pages.id', 'pages.site_id'], name=op.f('fk_experiments_page_id_pages'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], name=op.f('fk_experiments_site_id_sites'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_experiments')),
    sa.UniqueConstraint('id', 'site_id', name='uq_experiments_id_site')
    )
    op.create_index(op.f('ix_experiments_site_id'), 'experiments', ['site_id'], unique=False)
    op.create_table('ga4_daily',
    sa.Column('page_id', sa.String(length=36), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('landing_page', sa.String(length=2048), nullable=False),
    sa.Column('channel', sa.String(length=100), nullable=False),
    sa.Column('sessions', sa.Integer(), nullable=False),
    sa.Column('key_events', sa.Float(), nullable=False),
    sa.Column('qualified_conversions', sa.Float(), nullable=True),
    sa.Column('conversion_value', sa.Float(), nullable=True),
    sa.Column('is_fixture', sa.Boolean(), nullable=False),
    sa.Column('quality_flags_json', sa.JSON(), nullable=False),
    sa.Column('site_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('conversion_value IS NULL OR conversion_value >= 0', name=op.f('ck_ga4_daily_value_nonnegative')),
    sa.CheckConstraint('qualified_conversions IS NULL OR qualified_conversions >= 0', name=op.f('ck_ga4_daily_qualified_nonnegative')),
    sa.CheckConstraint('sessions >= 0 AND key_events >= 0', name=op.f('ck_ga4_daily_nonnegative_metrics')),
    sa.ForeignKeyConstraint(['page_id', 'site_id'], ['pages.id', 'pages.site_id'], name=op.f('fk_ga4_daily_page_id_pages'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], name=op.f('fk_ga4_daily_site_id_sites'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ga4_daily')),
    sa.UniqueConstraint('id', 'site_id', name='uq_ga4_daily_id_site'),
    sa.UniqueConstraint('site_id', 'date', 'landing_page', 'channel', name=op.f('uq_ga4_daily_site_id'))
    )
    op.create_index(op.f('ix_ga4_daily_site_id'), 'ga4_daily', ['site_id'], unique=False)
    op.create_index('ix_ga4_site_date', 'ga4_daily', ['site_id', 'date'], unique=False)
    op.create_table('gsc_daily',
    sa.Column('page_id', sa.String(length=36), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('page_url', sa.String(length=2048), nullable=False),
    sa.Column('query', sa.String(length=2048), nullable=False),
    sa.Column('country', sa.String(length=8), nullable=False),
    sa.Column('device', sa.String(length=30), nullable=False),
    sa.Column('clicks', sa.Integer(), nullable=False),
    sa.Column('impressions', sa.Integer(), nullable=False),
    sa.Column('position', sa.Float(), nullable=False),
    sa.Column('data_state', sa.String(length=20), nullable=False),
    sa.Column('is_fixture', sa.Boolean(), nullable=False),
    sa.Column('quality_flags_json', sa.JSON(), nullable=False),
    sa.Column('site_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('clicks >= 0 AND impressions >= 0 AND position >= 0', name=op.f('ck_gsc_daily_nonnegative_metrics')),
    sa.ForeignKeyConstraint(['page_id', 'site_id'], ['pages.id', 'pages.site_id'], name=op.f('fk_gsc_daily_page_id_pages'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], name=op.f('fk_gsc_daily_site_id_sites'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gsc_daily')),
    sa.UniqueConstraint('id', 'site_id', name='uq_gsc_daily_id_site'),
    sa.UniqueConstraint('site_id', 'date', 'page_url', 'query', 'country', 'device', name=op.f('uq_gsc_daily_site_id'))
    )
    op.create_index(op.f('ix_gsc_daily_site_id'), 'gsc_daily', ['site_id'], unique=False)
    op.create_index('ix_gsc_site_date', 'gsc_daily', ['site_id', 'date'], unique=False)
    op.create_table('opportunities',
    sa.Column('page_id', sa.String(length=36), nullable=True),
    sa.Column('page_url', sa.String(length=2048), nullable=False),
    sa.Column('kind', sa.String(length=100), nullable=False),
    sa.Column('finding', sa.Text(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('components_json', sa.JSON(), nullable=False),
    sa.Column('evidence_ids_json', sa.JSON(), nullable=False),
    sa.Column('evidence_json', sa.JSON(), nullable=False),
    sa.Column('quality_flags_json', sa.JSON(), nullable=False),
    sa.Column('recommended_action', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('dedup_key', sa.String(length=64), nullable=True),
    sa.Column('site_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['page_id', 'site_id'], ['pages.id', 'pages.site_id'], name=op.f('fk_opportunities_page_id_pages'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], name=op.f('fk_opportunities_site_id_sites'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_opportunities')),
    sa.UniqueConstraint('id', 'site_id', name='uq_opportunities_id_site'),
    sa.UniqueConstraint('site_id', 'dedup_key', name=op.f('uq_opportunities_site_id'))
    )
    op.create_index('ix_opportunities_rank', 'opportunities', ['site_id', 'status', 'score'], unique=False)
    op.create_index(op.f('ix_opportunities_site_id'), 'opportunities', ['site_id'], unique=False)
    op.create_table('page_entities',
    sa.Column('page_id', sa.String(length=36), nullable=False),
    sa.Column('entity_name', sa.String(length=250), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('attributes_json', sa.JSON(), nullable=False),
    sa.Column('site_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['page_id', 'site_id'], ['pages.id', 'pages.site_id'], name=op.f('fk_page_entities_page_id_pages'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], name=op.f('fk_page_entities_site_id_sites'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_page_entities')),
    sa.UniqueConstraint('id', 'site_id', name='uq_page_entities_id_site'),
    sa.UniqueConstraint('page_id', 'entity_name', 'entity_type', name=op.f('uq_page_entities_page_id'))
    )
    op.create_index(op.f('ix_page_entities_site_id'), 'page_entities', ['site_id'], unique=False)
    op.create_table('queries',
    sa.Column('text', sa.String(length=2048), nullable=False),
    sa.Column('cluster_id', sa.String(length=36), nullable=True),
    sa.Column('is_brand', sa.Boolean(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('site_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id', 'site_id'], ['query_clusters.id', 'query_clusters.site_id'], name=op.f('fk_queries_cluster_id_query_clusters'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], name=op.f('fk_queries_site_id_sites'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_queries')),
    sa.UniqueConstraint('id', 'site_id', name='uq_queries_id_site'),
    sa.UniqueConstraint('site_id', 'text', name=op.f('uq_queries_site_id'))
    )
    op.create_index(op.f('ix_queries_site_id'), 'queries', ['site_id'], unique=False)
    op.create_table('calibration_records',
    sa.Column('experiment_id', sa.String(length=36), nullable=True),
    sa.Column('agent_name', sa.String(length=100), nullable=False),
    sa.Column('action_category', sa.String(length=100), nullable=False),
    sa.Column('predicted_confidence', sa.Float(), nullable=False),
    sa.Column('succeeded', sa.Boolean(), nullable=True),
    sa.Column('brier_score', sa.Float(), nullable=True),
    sa.Column('evaluable', sa.Boolean(), nullable=False),
    sa.Column('exclusion_reason', sa.Text(), nullable=True),
    sa.Column('outcome_json', sa.JSON(), nullable=False),
    sa.Column('site_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('predicted_confidence BETWEEN 0 AND 1', name=op.f('ck_calibration_records_confidence_range')),
    sa.ForeignKeyConstraint(['experiment_id', 'site_id'], ['experiments.id', 'experiments.site_id'], name=op.f('fk_calibration_records_experiment_id_experiments'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], name=op.f('fk_calibration_records_site_id_sites'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_calibration_records')),
    sa.UniqueConstraint('id', 'site_id', name='uq_calibration_records_id_site')
    )
    op.create_index(op.f('ix_calibration_records_site_id'), 'calibration_records', ['site_id'], unique=False)
    op.create_table('crawl_issues',
    sa.Column('crawl_snapshot_id', sa.String(length=36), nullable=True),
    sa.Column('page_id', sa.String(length=36), nullable=True),
    sa.Column('kind', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('details_json', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('site_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['crawl_snapshot_id', 'site_id'], ['crawl_snapshots.id', 'crawl_snapshots.site_id'], name=op.f('fk_crawl_issues_crawl_snapshot_id_crawl_snapshots'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['page_id', 'site_id'], ['pages.id', 'pages.site_id'], name=op.f('fk_crawl_issues_page_id_pages'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], name=op.f('fk_crawl_issues_site_id_sites'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_crawl_issues')),
    sa.UniqueConstraint('id', 'site_id', name='uq_crawl_issues_id_site')
    )
    op.create_index(op.f('ix_crawl_issues_site_id'), 'crawl_issues', ['site_id'], unique=False)
    op.create_table('experiment_metrics',
    sa.Column('experiment_id', sa.String(length=36), nullable=False),
    sa.Column('checkpoint_days', sa.Integer(), nullable=False),
    sa.Column('metric', sa.String(length=200), nullable=False),
    sa.Column('observed_value', sa.Float(), nullable=True),
    sa.Column('sample_size', sa.Integer(), nullable=True),
    sa.Column('analysis_json', sa.JSON(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('site_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id', 'site_id'], ['experiments.id', 'experiments.site_id'], name=op.f('fk_experiment_metrics_experiment_id_experiments'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], name=op.f('fk_experiment_metrics_site_id_sites'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_experiment_metrics')),
    sa.UniqueConstraint('id', 'site_id', name='uq_experiment_metrics_id_site')
    )
    op.create_index(op.f('ix_experiment_metrics_site_id'), 'experiment_metrics', ['site_id'], unique=False)
    op.create_table('revisions',
    sa.Column('page_id', sa.String(length=36), nullable=True),
    sa.Column('kind', sa.String(length=100), nullable=False),
    sa.Column('changes_json', sa.JSON(), nullable=False),
    sa.Column('before_json', sa.JSON(), nullable=False),
    sa.Column('after_json', sa.JSON(), nullable=False),
    sa.Column('before_hash', sa.String(length=64), nullable=False),
    sa.Column('revision_hash', sa.String(length=64), nullable=False),
    sa.Column('evidence_ids_json', sa.JSON(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_by', sa.String(length=200), nullable=False),
    sa.Column('experiment_id', sa.String(length=36), nullable=True),
    sa.Column('site_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id', 'site_id'], ['experiments.id', 'experiments.site_id'], name=op.f('fk_revisions_experiment_id_experiments'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['page_id', 'site_id'], ['pages.id', 'pages.site_id'], name=op.f('fk_revisions_page_id_pages'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], name=op.f('fk_revisions_site_id_sites'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_revisions')),
    sa.UniqueConstraint('id', 'site_id', 'revision_hash', name='uq_revision_binding'),
    sa.UniqueConstraint('id', 'site_id', name='uq_revisions_id_site')
    )
    op.create_index(op.f('ix_revisions_site_id'), 'revisions', ['site_id'], unique=False)
    op.create_table('tasks',
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('objective', sa.Text(), nullable=False),
    sa.Column('opportunity_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('priority', sa.Float(), nullable=False),
    sa.Column('contract_json', sa.JSON(), nullable=False),
    sa.Column('result_json', sa.JSON(), nullable=True),
    sa.Column('site_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id', 'site_id'], ['opportunities.id', 'opportunities.site_id'], name=op.f('fk_tasks_opportunity_id_opportunities'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], name=op.f('fk_tasks_site_id_sites'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tasks')),
    sa.UniqueConstraint('id', 'site_id', name='uq_tasks_id_site')
    )
    op.create_index(op.f('ix_tasks_site_id'), 'tasks', ['site_id'], unique=False)
    op.create_table('actions',
    sa.Column('revision_id', sa.String(length=36), nullable=True),
    sa.Column('batch_id', sa.String(length=36), nullable=True),
    sa.Column('kind', sa.String(length=100), nullable=False),
    sa.Column('risk', sa.String(length=20), nullable=False),
    sa.Column('actor', sa.String(length=200), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('experiment_id', sa.String(length=36), nullable=True),
    sa.Column('idempotency_key', sa.String(length=200), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('site_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("risk IN ('LOW','MEDIUM','HIGH','CRITICAL')", name=op.f('ck_actions_risk')),
    sa.ForeignKeyConstraint(['batch_id', 'site_id'], ['action_batches.id', 'action_batches.site_id'], name=op.f('fk_actions_batch_id_action_batches'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['experiment_id', 'site_id'], ['experiments.id', 'experiments.site_id'], name=op.f('fk_actions_experiment_id_experiments'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['revision_id', 'site_id'], ['revisions.id', 'revisions.site_id'], name=op.f('fk_actions_revision_id_revisions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], name=op.f('fk_actions_site_id_sites'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_actions')),
    sa.UniqueConstraint('id', 'site_id', name='uq_actions_id_site'),
    sa.UniqueConstraint('site_id', 'idempotency_key', name=op.f('uq_actions_site_id'))
    )
    op.create_index(op.f('ix_actions_site_id'), 'actions', ['site_id'], unique=False)
    op.create_table('agent_runs',
    sa.Column('task_id', sa.String(length=36), nullable=True),
    sa.Column('agent_name', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('mode', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('contract_json', sa.JSON(), nullable=False),
    sa.Column('result_json', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('trace_id', sa.String(length=100), nullable=True),
    sa.Column('site_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], name=op.f('fk_agent_runs_site_id_sites'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['task_id', 'site_id'], ['tasks.id', 'tasks.site_id'], name=op.f('fk_agent_runs_task_id_tasks'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_runs')),
    sa.UniqueConstraint('id', 'site_id', name='uq_agent_runs_id_site')
    )
    op.create_index(op.f('ix_agent_runs_site_id'), 'agent_runs', ['site_id'], unique=False)
    op.create_table('approvals',
    sa.Column('revision_id', sa.String(length=36), nullable=False),
    sa.Column('revision_hash', sa.String(length=64), nullable=False),
    sa.Column('approved_by', sa.String(length=200), nullable=False),
    sa.Column('decision', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('site_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("decision IN ('APPROVE','REJECT','REVOKE')", name=op.f('ck_approvals_decision')),
    sa.ForeignKeyConstraint(['revision_id', 'site_id', 'revision_hash'], ['revisions.id', 'revisions.site_id', 'revisions.revision_hash'], name=op.f('fk_approvals_revision_id_revisions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], name=op.f('fk_approvals_site_id_sites'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_approvals')),
    sa.UniqueConstraint('id', 'site_id', name='uq_approvals_id_site')
    )
    op.create_index(op.f('ix_approvals_site_id'), 'approvals', ['site_id'], unique=False)
    op.create_table('task_dependencies',
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('depends_on_id', sa.String(length=36), nullable=False),
    sa.Column('site_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('task_id <> depends_on_id', name=op.f('ck_task_dependencies_no_self_dependency')),
    sa.ForeignKeyConstraint(['depends_on_id', 'site_id'], ['tasks.id', 'tasks.site_id'], name=op.f('fk_task_dependencies_depends_on_id_tasks'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], name=op.f('fk_task_dependencies_site_id_sites'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['task_id', 'site_id'], ['tasks.id', 'tasks.site_id'], name=op.f('fk_task_dependencies_task_id_tasks'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_task_dependencies')),
    sa.UniqueConstraint('id', 'site_id', name='uq_task_dependencies_id_site'),
    sa.UniqueConstraint('task_id', 'depends_on_id', name=op.f('uq_task_dependencies_task_id'))
    )
    op.create_index(op.f('ix_task_dependencies_site_id'), 'task_dependencies', ['site_id'], unique=False)
    op.create_table('task_ownership',
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('owner', sa.String(length=200), nullable=False),
    sa.Column('token', sa.String(length=36), nullable=False),
    sa.Column('acquired_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fencing_token', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], name=op.f('fk_task_ownership_site_id_sites'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['task_id', 'site_id'], ['tasks.id', 'tasks.site_id'], name=op.f('fk_task_ownership_task_id_tasks'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_task_ownership')),
    sa.UniqueConstraint('id', 'site_id', name='uq_task_ownership_id_site'),
    sa.UniqueConstraint('task_id', name=op.f('uq_task_ownership_task_id'))
    )
    op.create_index(op.f('ix_task_ownership_site_id'), 'task_ownership', ['site_id'], unique=False)
    op.create_table('verifications',
    sa.Column('revision_id', sa.String(length=36), nullable=False),
    sa.Column('revision_hash', sa.String(length=64), nullable=False),
    sa.Column('verifier_id', sa.String(length=200), nullable=False),
    sa.Column('verdict', sa.String(length=30), nullable=False),
    sa.Column('independent', sa.Boolean(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('action_safe', sa.Boolean(), nullable=False),
    sa.Column('packet_json', sa.JSON(), nullable=False),
    sa.Column('site_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("verdict IN ('PASS', 'BLOCK', 'NEEDS_EVIDENCE')", name=op.f('ck_verifications_verdict')),
    sa.CheckConstraint('confidence BETWEEN 0 AND 1', name=op.f('ck_verifications_confidence_range')),
    sa.ForeignKeyConstraint(['revision_id', 'site_id', 'revision_hash'], ['revisions.id', 'revisions.site_id', 'revisions.revision_hash'], name=op.f('fk_verifications_revision_id_revisions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], name=op.f('fk_verifications_site_id_sites'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_verifications')),
    sa.UniqueConstraint('id', 'site_id', name='uq_verifications_id_site')
    )
    op.create_index(op.f('ix_verifications_site_id'), 'verifications', ['site_id'], unique=False)
    op.create_table('action_events',
    sa.Column('action_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('details_json', sa.JSON(), nullable=False),
    sa.Column('site_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['action_id', 'site_id'], ['actions.id', 'actions.site_id'], name=op.f('fk_action_events_action_id_actions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], name=op.f('fk_action_events_site_id_sites'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_action_events')),
    sa.UniqueConstraint('id', 'site_id', name='uq_action_events_id_site')
    )
    op.create_index('ix_action_events_history', 'action_events', ['action_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_action_events_site_id'), 'action_events', ['site_id'], unique=False)
    op.create_table('agent_findings',
    sa.Column('agent_run_id', sa.String(length=36), nullable=False),
    sa.Column('claim_id', sa.String(length=36), nullable=True),
    sa.Column('packet_json', sa.JSON(), nullable=False),
    sa.Column('site_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_run_id', 'site_id'], ['agent_runs.id', 'agent_runs.site_id'], name=op.f('fk_agent_findings_agent_run_id_agent_runs'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['claim_id', 'site_id'], ['claims.id', 'claims.site_id'], name=op.f('fk_agent_findings_claim_id_claims'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], name=op.f('fk_agent_findings_site_id_sites'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_findings')),
    sa.UniqueConstraint('id', 'site_id', name='uq_agent_findings_id_site')
    )
    op.create_index(op.f('ix_agent_findings_site_id'), 'agent_findings', ['site_id'], unique=False)
    op.create_table('decision_logs',
    sa.Column('action_id', sa.String(length=36), nullable=True),
    sa.Column('decision', sa.Text(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('owner', sa.String(length=200), nullable=False),
    sa.Column('evidence_ids_json', sa.JSON(), nullable=False),
    sa.Column('alternatives_json', sa.JSON(), nullable=False),
    sa.Column('uncertainty_json', sa.JSON(), nullable=False),
    sa.Column('regret_json', sa.JSON(), nullable=False),
    sa.Column('site_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['action_id', 'site_id'], ['actions.id', 'actions.site_id'], name=op.f('fk_decision_logs_action_id_actions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], name=op.f('fk_decision_logs_site_id_sites'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_decision_logs')),
    sa.UniqueConstraint('id', 'site_id', name='uq_decision_logs_id_site')
    )
    op.create_index(op.f('ix_decision_logs_site_id'), 'decision_logs', ['site_id'], unique=False)
    op.create_table('execution_leases',
    sa.Column('page_id', sa.String(length=36), nullable=False),
    sa.Column('action_id', sa.String(length=36), nullable=False),
    sa.Column('owner', sa.String(length=200), nullable=False),
    sa.Column('token', sa.String(length=36), nullable=False),
    sa.Column('site_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['action_id', 'site_id'], ['actions.id', 'actions.site_id'], name=op.f('fk_execution_leases_action_id_actions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['page_id', 'site_id'], ['pages.id', 'pages.site_id'], name=op.f('fk_execution_leases_page_id_pages'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], name=op.f('fk_execution_leases_site_id_sites'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_execution_leases')),
    sa.UniqueConstraint('id', 'site_id', name='uq_execution_leases_id_site'),
    sa.UniqueConstraint('site_id', 'page_id', name=op.f('uq_execution_leases_site_id'))
    )
    op.create_index(op.f('ix_execution_leases_site_id'), 'execution_leases', ['site_id'], unique=False)
    op.create_table('failure_cases',
    sa.Column('action_id', sa.String(length=36), nullable=True),
    sa.Column('agent_run_id', sa.String(length=36), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('predicted', sa.Text(), nullable=False),
    sa.Column('actual', sa.Text(), nullable=False),
    sa.Column('magnitude', sa.Float(), nullable=True),
    sa.Column('root_cause', sa.Text(), nullable=False),
    sa.Column('incorrect_assumption', sa.Text(), nullable=False),
    sa.Column('missing_evidence', sa.Text(), nullable=False),
    sa.Column('agent_responsible', sa.String(length=200), nullable=False),
    sa.Column('detection_method', sa.Text(), nullable=False),
    sa.Column('preventative_change', sa.Text(), nullable=False),
    sa.Column('guardrail_change_required', sa.Boolean(), nullable=False),
    sa.Column('details_json', sa.JSON(), nullable=False),
    sa.Column('site_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['action_id', 'site_id'], ['actions.id', 'actions.site_id'], name=op.f('fk_failure_cases_action_id_actions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['agent_run_id', 'site_id'], ['agent_runs.id', 'agent_runs.site_id'], name=op.f('fk_failure_cases_agent_run_id_agent_runs'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], name=op.f('fk_failure_cases_site_id_sites'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_failure_cases')),
    sa.UniqueConstraint('id', 'site_id', name='uq_failure_cases_id_site')
    )
    op.create_index(op.f('ix_failure_cases_site_id'), 'failure_cases', ['site_id'], unique=False)
    op.create_table('guardrails',
    sa.Column('action_id', sa.String(length=36), nullable=True),
    sa.Column('rule', sa.String(length=200), nullable=False),
    sa.Column('outcome', sa.String(length=30), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('context_json', sa.JSON(), nullable=False),
    sa.Column('site_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['action_id', 'site_id'], ['actions.id', 'actions.site_id'], name=op.f('fk_guardrails_action_id_actions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], name=op.f('fk_guardrails_site_id_sites'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_guardrails')),
    sa.UniqueConstraint('id', 'site_id', name='uq_guardrails_id_site')
    )
    op.create_index(op.f('ix_guardrails_site_id'), 'guardrails', ['site_id'], unique=False)
    op.create_table('page_versions',
    sa.Column('page_id', sa.String(length=36), nullable=False),
    sa.Column('action_id', sa.String(length=36), nullable=True),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('content_json', sa.JSON(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('site_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['action_id', 'site_id'], ['actions.id', 'actions.site_id'], name=op.f('fk_page_versions_action_id_actions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['page_id', 'site_id'], ['pages.id', 'pages.site_id'], name=op.f('fk_page_versions_page_id_pages'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], name=op.f('fk_page_versions_site_id_sites'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_page_versions')),
    sa.UniqueConstraint('id', 'site_id', name='uq_page_versions_id_site'),
    sa.UniqueConstraint('page_id', 'version_number', name=op.f('uq_page_versions_page_id'))
    )
    op.create_index(op.f('ix_page_versions_site_id'), 'page_versions', ['site_id'], unique=False)
    op.create_table('rollback_events',
    sa.Column('action_id', sa.String(length=36), nullable=False),
    sa.Column('rollback_action_id', sa.String(length=36), nullable=True),
    sa.Column('page_version_id', sa.String(length=36), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('actor', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('details_json', sa.JSON(), nullable=False),
    sa.Column('site_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['action_id', 'site_id'], ['actions.id', 'actions.site_id'], name=op.f('fk_rollback_events_action_id_actions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['page_version_id', 'site_id'], ['page_versions.id', 'page_versions.site_id'], name=op.f('fk_rollback_events_page_version_id_page_versions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['rollback_action_id', 'site_id'], ['actions.id', 'actions.site_id'], name=op.f('fk_rollback_events_rollback_action_id_actions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], name=op.f('fk_rollback_events_site_id_sites'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rollback_events')),
    sa.UniqueConstraint('id', 'site_id', name='uq_rollback_events_id_site')
    )
    op.create_index(op.f('ix_rollback_events_site_id'), 'rollback_events', ['site_id'], unique=False)
    # ### end Alembic commands ###
    _audit_triggers()


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rollback_events_site_id'), table_name='rollback_events')
    op.drop_table('rollback_events')
    op.drop_index(op.f('ix_page_versions_site_id'), table_name='page_versions')
    op.drop_table('page_versions')
    op.drop_index(op.f('ix_guardrails_site_id'), table_name='guardrails')
    op.drop_table('guardrails')
    op.drop_index(op.f('ix_failure_cases_site_id'), table_name='failure_cases')
    op.drop_table('failure_cases')
    op.drop_index(op.f('ix_execution_leases_site_id'), table_name='execution_leases')
    op.drop_table('execution_leases')
    op.drop_index(op.f('ix_decision_logs_site_id'), table_name='decision_logs')
    op.drop_table('decision_logs')
    op.drop_index(op.f('ix_agent_findings_site_id'), table_name='agent_findings')
    op.drop_table('agent_findings')
    op.drop_index(op.f('ix_action_events_site_id'), table_name='action_events')
    op.drop_index('ix_action_events_history', table_name='action_events')
    op.drop_table('action_events')
    op.drop_index(op.f('ix_verifications_site_id'), table_name='verifications')
    op.drop_table('verifications')
    op.drop_index(op.f('ix_task_ownership_site_id'), table_name='task_ownership')
    op.drop_table('task_ownership')
    op.drop_index(op.f('ix_task_dependencies_site_id'), table_name='task_dependencies')
    op.drop_table('task_dependencies')
    op.drop_index(op.f('ix_approvals_site_id'), table_name='approvals')
    op.drop_table('approvals')
    op.drop_index(op.f('ix_agent_runs_site_id'), table_name='agent_runs')
    op.drop_table('agent_runs')
    op.drop_index(op.f('ix_actions_site_id'), table_name='actions')
    op.drop_table('actions')
    op.drop_index(op.f('ix_tasks_site_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_revisions_site_id'), table_name='revisions')
    op.drop_table('revisions')
    op.drop_index(op.f('ix_experiment_metrics_site_id'), table_name='experiment_metrics')
    op.drop_table('experiment_metrics')
    op.drop_index(op.f('ix_crawl_issues_site_id'), table_name='crawl_issues')
    op.drop_table('crawl_issues')
    op.drop_index(op.f('ix_calibration_records_site_id'), table_name='calibration_records')
    op.drop_table('calibration_records')
    op.drop_index(op.f('ix_queries_site_id'), table_name='queries')
    op.drop_table('queries')
    op.drop_index(op.f('ix_page_entities_site_id'), table_name='page_entities')
    op.drop_table('page_entities')
    op.drop_index(op.f('ix_opportunities_site_id'), table_name='opportunities')
    op.drop_index('ix_opportunities_rank', table_name='opportunities')
    op.drop_table('opportunities')
    op.drop_index('ix_gsc_site_date', table_name='gsc_daily')
    op.drop_index(op.f('ix_gsc_daily_site_id'), table_name='gsc_daily')
    op.drop_table('gsc_daily')
    op.drop_index('ix_ga4_site_date', table_name='ga4_daily')
    op.drop_index(op.f('ix_ga4_daily_site_id'), table_name='ga4_daily')
    op.drop_table('ga4_daily')
    op.drop_index(op.f('ix_experiments_site_id'), table_name='experiments')
    op.drop_table('experiments')
    op.drop_index(op.f('ix_crawl_snapshots_site_id'), table_name='crawl_snapshots')
    op.drop_table('crawl_snapshots')
    op.drop_index(op.f('ix_contradictions_site_id'), table_name='contradictions')
    op.drop_table('contradictions')
    op.drop_index(op.f('ix_claim_evidence_site_id'), table_name='claim_evidence')
    op.drop_table('claim_evidence')
    op.drop_index(op.f('ix_strategy_versions_site_id'), table_name='strategy_versions')
    op.drop_table('strategy_versions')
    op.drop_index(op.f('ix_serp_snapshots_site_id'), table_name='serp_snapshots')
    op.drop_index('ix_serp_site_query', table_name='serp_snapshots')
    op.drop_table('serp_snapshots')
    op.drop_index(op.f('ix_query_clusters_site_id'), table_name='query_clusters')
    op.drop_table('query_clusters')
    op.drop_index(op.f('ix_policies_site_id'), table_name='policies')
    op.drop_table('policies')
    op.drop_index(op.f('ix_pages_site_id'), table_name='pages')
    op.drop_table('pages')
    op.drop_index(op.f('ix_mission_states_site_id'), table_name='mission_states')
    op.drop_table('mission_states')
    op.drop_index(op.f('ix_job_runs_site_id'), table_name='job_runs')
    op.drop_table('job_runs')
    op.drop_index(op.f('ix_job_leases_expires_at'), table_name='job_leases')
    op.drop_table('job_leases')
    op.drop_index(op.f('ix_evidence_site_id'), table_name='evidence')
    op.drop_table('evidence')
    op.drop_index(op.f('ix_claims_site_id'), table_name='claims')
    op.drop_table('claims')
    op.drop_index(op.f('ix_assumptions_site_id'), table_name='assumptions')
    op.drop_table('assumptions')
    op.drop_index(op.f('ix_ai_search_snapshots_site_id'), table_name='ai_search_snapshots')
    op.drop_table('ai_search_snapshots')
    op.drop_index(op.f('ix_action_batches_site_id'), table_name='action_batches')
    op.drop_table('action_batches')
    op.drop_table('sites')
    # ### end Alembic commands ###
    if op.get_bind().dialect.name == "postgresql":
        op.execute("DROP FUNCTION IF EXISTS seo_reject_audit_mutation()")
